// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOUkcnffaQIxx5arp_8ugEmo26GAZrKzo',
    appId: '1:407906170760:web:ff871d4d6e109d5580ec3d',
    messagingSenderId: '407906170760',
    projectId: 'movies-app-cf83d',
    authDomain: 'movies-app-cf83d.firebaseapp.com',
    storageBucket: 'movies-app-cf83d.firebasestorage.app',
    measurementId: 'G-PYTJ1SD7Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexDUySyNDfHwZMol3m-TeLUQKMde56q0',
    appId: '1:407906170760:android:3a1ddf0bf45b4a6f80ec3d',
    messagingSenderId: '407906170760',
    projectId: 'movies-app-cf83d',
    storageBucket: 'movies-app-cf83d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8-QFb_BwnrNv8MMtIk1qMSvTUZMJs-zo',
    appId: '1:407906170760:ios:c9fc821cd7e906a980ec3d',
    messagingSenderId: '407906170760',
    projectId: 'movies-app-cf83d',
    storageBucket: 'movies-app-cf83d.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8-QFb_BwnrNv8MMtIk1qMSvTUZMJs-zo',
    appId: '1:407906170760:ios:c9fc821cd7e906a980ec3d',
    messagingSenderId: '407906170760',
    projectId: 'movies-app-cf83d',
    storageBucket: 'movies-app-cf83d.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOUkcnffaQIxx5arp_8ugEmo26GAZrKzo',
    appId: '1:407906170760:web:af44177d76c0322880ec3d',
    messagingSenderId: '407906170760',
    projectId: 'movies-app-cf83d',
    authDomain: 'movies-app-cf83d.firebaseapp.com',
    storageBucket: 'movies-app-cf83d.firebasestorage.app',
    measurementId: 'G-TRHE5RRYX2',
  );
}
